{
  "formatVersion": "1.1",
  "component": {
    "group": "com.modularization.plugin",
    "module": "GradlePlugin",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "GradlePlugin-1.0.jar",
          "url": "GradlePlugin-1.0.jar",
          "size": 4000,
          "sha512": "4960f66ae2a84f74ad4f588787ccadf5d3533981eb0cd30437af4667038441f972f4d8229012007a40970f6f69c586a69412ade747ee2fdfe2901f90758144b9",
          "sha256": "7e1d547dcacac672c130ec761445288f71e4e3e36e1f9076616395e78cbaf7c7",
          "sha1": "cd0c5dfb64cea76a13a091137d9654e8bc364b08",
          "md5": "f49967777b803ec2d62ce15de09b4272"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "GradlePlugin-1.0.jar",
          "url": "GradlePlugin-1.0.jar",
          "size": 4000,
          "sha512": "4960f66ae2a84f74ad4f588787ccadf5d3533981eb0cd30437af4667038441f972f4d8229012007a40970f6f69c586a69412ade747ee2fdfe2901f90758144b9",
          "sha256": "7e1d547dcacac672c130ec761445288f71e4e3e36e1f9076616395e78cbaf7c7",
          "sha1": "cd0c5dfb64cea76a13a091137d9654e8bc364b08",
          "md5": "f49967777b803ec2d62ce15de09b4272"
        }
      ]
    }
  ]
}
